# Generated by Django 5.1.3 on 2024-11-11 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweetmodel_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tweets.tweetmodel'),
        ),
    ]
